services:
  mysql:
    container_name: mysql_usabilidad
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: javaweb
    volumes:
      - ./deploy/my.cnf:/etc/mysql/conf.d/my.cnf:ro  # Volumen de solo lectura
      - ./deploy/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"
  python-server:
    container_name: python_usabilidad
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./python_app:/app  # Carpeta para tus archivos Python y HTML
    ports:
      - "5000:5000"
    command: sh -c "pip install -r requirements.txt && python app.py"
    restart: always


volumes:
  maven_target:

