services:
  mysql:
    container_name: mysql_usabilidad
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: accesibilidad
    volumes:
      - ./deploy/my.cnf:/etc/mysql/conf.d/my.cnf:ro  # Volumen de solo lectura
      - ./deploy/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"

  python-server:
    container_name: python_usabilidad
    build:
      context: ./python_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python_app:/app  # Carpeta para tus archivos Python y HTML
    command: sh -c "pip install -r requirements.txt && python app.py"
    restart: always
